### ISSUE TITLE
Want to contribute a remove "X-Powered-By" Middleware and a DoublePassProxy

### ISSUE THREAD

**Issue by Byteceptikus** [middlewares/psr15-middlewares#4]
Hello,

how is the workflow to contribute to the middleware "namespace" a new package?

I have written a simple remove "X-Powered-By" middleware and a Proxy/Adapter to use PSR-15 middlewares with the current Slim version with it's double pass syntax. Slim 4 is going to use also PSR-15...

**Comment by oscarotero** [comment]
Hello.
First, thanks for the contribution :)

You should use [this skeleton](https://github.com/middlewares/skeleton) to create the packages.
Then, the package can be transfered to this organization, if we think they're useful.

I'm not sure about the `X-Powered-By` middleware, because it's too simple and this header must be removed using a [php.ini directive](http://stackoverflow.com/questions/2661799/removing-x-powered-by#2661807). Maybe, a more flexible middleware could be one to add or remove any header. Example:

```php
use Middlewares\Headers;

$middleware[] = (new Headers())
    ->add($headersToAdd)
    ->replace($headersToReplace)
    ->remove($headersToRemove);
```

And about the Adapter to use PSR-15 midddlewares, I think this should be implemented by Slim (the same for any other framework with double-pass signature). This organization is focused to provide PSR-15 middlewares for PSR-15 compatible dispatchers.

Thank you

**Comment by Byteceptikus** [comment]
Ok - Can be closed ;)
